---
- name: Create Users and Set Permissions
  hosts: all
  become: yes
  tasks:
  - name: Create a new user
    user:
      name: "{{ item.username }}"
      state: present
      shell: /bin/bash
    loop:
     - { username: "harish" }
     - { username: "arun" }
  - name: Create directory and set permissions
    file:
      path: "/home/{{ item.username }}/shared"
      state: directory
      mode: '0775'
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
    loop:
      - { username: "harish" }
      - { username: "arun" }
